import { useQuery } from '@apollo/client';
import gql from 'graphql-tag';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from "next/image";
import ProductCard from '../components/ProductCard';
import MaxWidth from '../components/MaxWidth';
import Banner from '../components/Banner';

export const ALL_PRODUCTS_QUERY = gql`
  query ALL_PRODUCTS_QUERY($skip: Int = 0, $first: Int) {
    allProducts(first: $first, skip: $skip) {
      id
      name
      price
      description
      photo {
        id
        image {
          publicUrlTransformed
        }
      }
    }
  }
`;

export default function Home() {
  const { data, loading, error } = useQuery(ALL_PRODUCTS_QUERY, {
    variables: {
      first: 4
    }
  })

  console.log(data?.allProducts[0])

  return (
    < >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MaxWidth>
        <Image src="/hero.png" height={461} width={1152} alt={"Banner Image"} className="mb-6 min-h-[364px] object-cover w-screen " ></Image>

        <div className=' p-6 xl:p-0 mb-6'>
          <h1 className='font-headline lg:text-4xl text-2xl  text-turquoise text-shadow-3d'>Explore Products</h1>
          <div className='grid grid-cols-2 lg:grid-cols-4 gap-8'>  {data && data.allProducts.map(product => <ProductCard product={product} key={product.id} />)}</div>
        </div>
      </MaxWidth>
      <Banner></Banner>
    </>
  )


}

